config/routes.rb
Mapapp::Application.routes.draw do
  resources :people do
    collection { post :import }
  end

  resources :leads_bs do
    collection { post :import }
  end

  resources :venues

  resources :leads_as do
    collection { post :import }
  end

  get "map/show"
  root :to =>  "map#show"

end

app/models/leads_a.rb
# == Schema Information
#
# Table name: leads_as
#
#  id         :integer          not null, primary key
#  Address1   :string(255)
#  Address2   :string(255)
#  Address3   :string(255)
#  Address4   :string(255)
#  FirstName  :string(255)
#  HomePhone  :string(255)
#  LastName   :string(255)
#  Postcode   :string(255)
#  Price      :string(255)
#  Title      :string(255)
#  Address5   :string(255)
#  Address6   :string(255)
#  gmaps      :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  latitude   :float
#  longitude  :float
#  Distance   :string(255)
#

class LeadsA < ActiveRecord::Base
  attr_accessible :venue, :Distance, :Price, :latitude, :longitude, :Address1, :Address2, :Address3, :Address4, :Address5, :Address6, :FirstName, :HomePhone, :LastName, :Postcode, :Price, :Title
  geocoded_by :Postcode   
  after_validation :geocode
  acts_as_gmappable :process_geocoding => false

def self.import(file)
	Thread.new do
  CSV.foreach(file.path, headers: true) do |row|
    LeadsA.create! row.to_hash
  end
end
end



end

app/controllers/leads_as_controller.rb
class LeadsAsController < ApplicationController
  # GET /leads_as
  # GET /leads_as.json

def import
  LeadsA.import(params[:file])
  redirect_to map_show, notice: "Leads imported."
end



  def index
    @leads_as = LeadsA.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leads_as }
    end
  end

  # GET /leads_as/1
  # GET /leads_as/1.json
  def show
    @leads_a = LeadsA.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @leads_a }
    end
  end

  # GET /leads_as/new
  # GET /leads_as/new.json
  def new
    @leads_a = LeadsA.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @leads_a }
    end
  end

  # GET /leads_as/1/edit
  def edit
    @leads_a = LeadsA.find(params[:id])
  end

  # POST /leads_as
  # POST /leads_as.json
  def create
    @leads_a = LeadsA.new(params[:leads_a])

    respond_to do |format|
      if @leads_a.save
        format.html { redirect_to @leads_a, notice: 'Leads a was successfully created.' }
        format.json { render json: @leads_a, status: :created, location: @leads_a }
      else
        format.html { render action: "new" }
        format.json { render json: @leads_a.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /leads_as/1
  # PUT /leads_as/1.json
  def update
    @leads_a = LeadsA.find(params[:id])

    respond_to do |format|
      if @leads_a.update_attributes(params[:leads_a])
        format.html { redirect_to @leads_a, notice: 'Leads a was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @leads_a.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads_as/1
  # DELETE /leads_as/1.json
  def destroy
    @leads_a = LeadsA.find(params[:id])
    @leads_a.destroy

    respond_to do |format|
      format.html { redirect_to leads_as_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/leads_as_helper.rb
module LeadsAsHelper
end

app/views/leads_as/_form.html.erb
<%= form_for(@leads_a) do |f| %>
  <% if @leads_a.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@leads_a.errors.count, "error") %> prohibited this leads_a from being saved:</h2>

      <ul>
      <% @leads_a.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Address1 %><br />
    <%= f.text_field :Address1 %>
  </div>
  <div class="field">
    <%= f.label :Address2 %><br />
    <%= f.text_field :Address2 %>
  </div>
  <div class="field">
    <%= f.label :Address3 %><br />
    <%= f.text_field :Address3 %>
  </div>
  <div class="field">
    <%= f.label :Address4 %><br />
    <%= f.text_field :Address4 %>
  </div>
  <div class="field">
    <%= f.label :FirstName %><br />
    <%= f.text_field :FirstName %>
  </div>
  <div class="field">
    <%= f.label :HomePhone %><br />
    <%= f.text_field :HomePhone %>
  </div>
  <div class="field">
    <%= f.label :LastName %><br />
    <%= f.text_field :LastName %>
  </div>
  <div class="field">
    <%= f.label :Postcode %><br />
    <%= f.text_field :Postcode %>
  </div>
  <div class="field">
    <%= f.label :Price %><br />
    <%= f.text_field :Price %>
  </div>
  <div class="field">
    <%= f.label :Title %><br />
    <%= f.text_field :Title %>
  </div>
  <div class="field">
    <%= f.label :Address5 %><br />
    <%= f.text_field :Address5 %>
  </div>
  <div class="field">
    <%= f.label :Address6 %><br />
    <%= f.text_field :Address6 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leads_as/edit.html.erb
<h1>Editing leads_a</h1>

<%= render 'form' %>

<%= link_to 'Show', @leads_a %> |
<%= link_to 'Back', leads_as_path %>

app/views/leads_as/index.html.erb
<h1>Listing leads_as</h1>

<h2>Import Leads</h2>
<%= form_tag import_leads_as_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

<table>
  <tr>
    <th>Address1</th>
    <th>Address2</th>
    <th>Address3</th>
    <th>Address4</th>
    <th>Firstname</th>
    <th>Homephone</th>
    <th>Lastname</th>
    <th>Postcode</th>
    <th>Price</th>
    <th>Title</th>
    <th>Address5</th>
    <th>Address6</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @leads_as.each do |leads_a| %>
  <tr>
    <td><%= leads_a.Address1 %></td>
    <td><%= leads_a.Address2 %></td>
    <td><%= leads_a.Address3 %></td>
    <td><%= leads_a.Address4 %></td>
    <td><%= leads_a.FirstName %></td>
    <td><%= leads_a.HomePhone %></td>
    <td><%= leads_a.LastName %></td>
    <td><%= leads_a.Postcode %></td>
    <td><%= leads_a.Price %></td>
    <td><%= leads_a.Title %></td>
    <td><%= leads_a.Address5 %></td>
    <td><%= leads_a.Address6 %></td>
    <td><%= link_to 'Show', leads_a %></td>
    <td><%= link_to 'Edit', edit_leads_a_path(leads_a) %></td>
    <td><%= link_to 'Destroy', leads_a, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Leads a', new_leads_a_path %>

app/views/leads_as/new.html.erb
<h1>New leads_a</h1>

<%= render 'form' %>

<%= link_to 'Back', leads_as_path %>

app/views/leads_as/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Address1:</b>
  <%= @leads_a.Address1 %>
</p>

<p>
  <b>Address2:</b>
  <%= @leads_a.Address2 %>
</p>

<p>
  <b>Address3:</b>
  <%= @leads_a.Address3 %>
</p>

<p>
  <b>Address4:</b>
  <%= @leads_a.Address4 %>
</p>

<p>
  <b>Firstname:</b>
  <%= @leads_a.FirstName %>
</p>

<p>
  <b>Homephone:</b>
  <%= @leads_a.HomePhone %>
</p>

<p>
  <b>Lastname:</b>
  <%= @leads_a.LastName %>
</p>

<p>
  <b>Postcode:</b>
  <%= @leads_a.Postcode %>
</p>

<p>
  <b>Price:</b>
  <%= @leads_a.Price %>
</p>

<p>
  <b>Title:</b>
  <%= @leads_a.Title %>
</p>

<p>
  <b>Address5:</b>
  <%= @leads_a.Address5 %>
</p>

<p>
  <b>Address6:</b>
  <%= @leads_a.Address6 %>
</p>


<%= link_to 'Edit', edit_leads_a_path(@leads_a) %> |
<%= link_to 'Back', leads_as_path %>