config/routes.rb
Mapapp::Application.routes.draw do
  resources :people do
    collection { post :import }
  end

  resources :leads_bs do
    collection { post :import }
  end

  resources :venues

  resources :leads_as do
    collection { post :import }
  end

  get "map/show"
  root :to =>  "map#show"

end

app/models/leads_b.rb
# == Schema Information
#
# Table name: leads_bs
#
#  id         :integer          not null, primary key
#  Address1   :string(255)
#  Address2   :string(255)
#  Address3   :string(255)
#  Address4   :string(255)
#  FirstName  :string(255)
#  HomePhone  :string(255)
#  LastName   :string(255)
#  Postcode   :string(255)
#  Price      :string(255)
#  Title      :string(255)
#  Address5   :string(255)
#  Address6   :string(255)
#  longitude  :float
#  latitude   :float
#  gmap       :boolean
#  Distance   :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  gmaps      :boolean
#

class LeadsB < ActiveRecord::Base
  attr_accessible :Distance, :Price, :latitude, :longitude, :Address1, :Address2, :Address3, :Address4, :Address5, :Address6, :FirstName, :HomePhone, :LastName, :Postcode, :Price, :Title
  geocoded_by :Postcode   
  after_validation :geocode
  acts_as_gmappable :process_geocoding => false 

 

def self.import(file)
  CSV.foreach(file.path, headers: true) do |row|
    LeadsB.create! row.to_hash
  end
end



end

app/controllers/leads_bs_controller.rb
class LeadsBsController < ApplicationController
  # GET /leads_bs
  # GET /leads_bs.json

def import
  LeadsB.import(params[:file])
  redirect_to map_show, notice: "Leads imported."
end

  def index
    @leads_bs = LeadsB.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leads_bs }
    end
  end

  # GET /leads_bs/1
  # GET /leads_bs/1.json
  def show
    @leads_b = LeadsB.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @leads_b }
    end
  end

  # GET /leads_bs/new
  # GET /leads_bs/new.json
  def new
    @leads_b = LeadsB.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @leads_b }
    end
  end

  # GET /leads_bs/1/edit
  def edit
    @leads_b = LeadsB.find(params[:id])
  end

  # POST /leads_bs
  # POST /leads_bs.json
  def create
    @leads_b = LeadsB.new(params[:leads_b])

    respond_to do |format|
      if @leads_b.save
        format.html { redirect_to @leads_b, notice: 'Leads b was successfully created.' }
        format.json { render json: @leads_b, status: :created, location: @leads_b }
      else
        format.html { render action: "new" }
        format.json { render json: @leads_b.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /leads_bs/1
  # PUT /leads_bs/1.json
  def update
    @leads_b = LeadsB.find(params[:id])

    respond_to do |format|
      if @leads_b.update_attributes(params[:leads_b])
        format.html { redirect_to @leads_b, notice: 'Leads b was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @leads_b.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads_bs/1
  # DELETE /leads_bs/1.json
  def destroy
    @leads_b = LeadsB.find(params[:id])
    @leads_b.destroy

    respond_to do |format|
      format.html { redirect_to leads_bs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/leads_bs_helper.rb
module LeadsBsHelper
end

app/views/leads_bs/_form.html.erb
<%= form_for(@leads_b) do |f| %>
  <% if @leads_b.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@leads_b.errors.count, "error") %> prohibited this leads_b from being saved:</h2>

      <ul>
      <% @leads_b.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Address1 %><br />
    <%= f.text_field :Address1 %>
  </div>
  <div class="field">
    <%= f.label :Address2 %><br />
    <%= f.text_field :Address2 %>
  </div>
  <div class="field">
    <%= f.label :Address3 %><br />
    <%= f.text_field :Address3 %>
  </div>
  <div class="field">
    <%= f.label :Address4 %><br />
    <%= f.text_field :Address4 %>
  </div>
  <div class="field">
    <%= f.label :FirstName %><br />
    <%= f.text_field :FirstName %>
  </div>
  <div class="field">
    <%= f.label :HomePhone %><br />
    <%= f.text_field :HomePhone %>
  </div>
  <div class="field">
    <%= f.label :LastName %><br />
    <%= f.text_field :LastName %>
  </div>
  <div class="field">
    <%= f.label :Postcode %><br />
    <%= f.text_field :Postcode %>
  </div>
  <div class="field">
    <%= f.label :Price %><br />
    <%= f.text_field :Price %>
  </div>
  <div class="field">
    <%= f.label :Title %><br />
    <%= f.text_field :Title %>
  </div>
  <div class="field">
    <%= f.label :Address5 %><br />
    <%= f.text_field :Address5 %>
  </div>
  <div class="field">
    <%= f.label :Address6 %><br />
    <%= f.text_field :Address6 %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :gmap %><br />
    <%= f.check_box :gmap %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :Distance %><br />
    <%= f.text_field :Distance %>
  </div>
  <div class="field">
    <%= f.label :Price %><br />
    <%= f.text_field :Price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leads_bs/edit.html.erb
<h1>Editing leads_b</h1>

<%= render 'form' %>

<%= link_to 'Show', @leads_b %> |
<%= link_to 'Back', leads_bs_path %>

app/views/leads_bs/index.html.erb
<h1>Listing leads_bs</h1>
<h2>Import Leads</h2>
<%= form_tag import_leads_bs_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>
<table>
  <tr>
    <th>Address1</th>
    <th>Address2</th>
    <th>Address3</th>
    <th>Address4</th>
    <th>Firstname</th>
    <th>Homephone</th>
    <th>Lastname</th>
    <th>Postcode</th>
    <th>Price</th>
    <th>Title</th>
    <th>Address5</th>
    <th>Address6</th>
    <th>Longitude</th>
    <th>Latitude</th>
    <th>Gmap</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Distance</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @leads_bs.each do |leads_b| %>
  <tr>
    <td><%= leads_b.Address1 %></td>
    <td><%= leads_b.Address2 %></td>
    <td><%= leads_b.Address3 %></td>
    <td><%= leads_b.Address4 %></td>
    <td><%= leads_b.FirstName %></td>
    <td><%= leads_b.HomePhone %></td>
    <td><%= leads_b.LastName %></td>
    <td><%= leads_b.Postcode %></td>
    <td><%= leads_b.Price %></td>
    <td><%= leads_b.Title %></td>
    <td><%= leads_b.Address5 %></td>
    <td><%= leads_b.Address6 %></td>
    <td><%= leads_b.longitude %></td>
    <td><%= leads_b.latitude %></td>
    <td><%= leads_b.gmap %></td>
    <td><%= leads_b.latitude %></td>
    <td><%= leads_b.longitude %></td>
    <td><%= leads_b.Distance %></td>
    <td><%= leads_b.Price %></td>
    <td><%= link_to 'Show', leads_b %></td>
    <td><%= link_to 'Edit', edit_leads_b_path(leads_b) %></td>
    <td><%= link_to 'Destroy', leads_b, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Leads b', new_leads_b_path %>

app/views/leads_bs/new.html.erb
<h1>New leads_b</h1>

<%= render 'form' %>

<%= link_to 'Back', leads_bs_path %>

app/views/leads_bs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Address1:</b>
  <%= @leads_b.Address1 %>
</p>

<p>
  <b>Address2:</b>
  <%= @leads_b.Address2 %>
</p>

<p>
  <b>Address3:</b>
  <%= @leads_b.Address3 %>
</p>

<p>
  <b>Address4:</b>
  <%= @leads_b.Address4 %>
</p>

<p>
  <b>Firstname:</b>
  <%= @leads_b.FirstName %>
</p>

<p>
  <b>Homephone:</b>
  <%= @leads_b.HomePhone %>
</p>

<p>
  <b>Lastname:</b>
  <%= @leads_b.LastName %>
</p>

<p>
  <b>Postcode:</b>
  <%= @leads_b.Postcode %>
</p>

<p>
  <b>Price:</b>
  <%= @leads_b.Price %>
</p>

<p>
  <b>Title:</b>
  <%= @leads_b.Title %>
</p>

<p>
  <b>Address5:</b>
  <%= @leads_b.Address5 %>
</p>

<p>
  <b>Address6:</b>
  <%= @leads_b.Address6 %>
</p>

<p>
  <b>Longitude:</b>
  <%= @leads_b.longitude %>
</p>

<p>
  <b>Latitude:</b>
  <%= @leads_b.latitude %>
</p>

<p>
  <b>Gmap:</b>
  <%= @leads_b.gmap %>
</p>

<p>
  <b>Latitude:</b>
  <%= @leads_b.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @leads_b.longitude %>
</p>

<p>
  <b>Distance:</b>
  <%= @leads_b.Distance %>
</p>

<p>
  <b>Price:</b>
  <%= @leads_b.Price %>
</p>


<%= link_to 'Edit', edit_leads_b_path(@leads_b) %> |
<%= link_to 'Back', leads_bs_path %>